//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: Envelope includes `deadline_unix` field, default = now() + 30s; --deadline-secs N overrides it.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac10_default() {
    let before = baton::now_unix();
    let out = Command::new(bin())
        .args(["--from", "t", "send", "x", "y", "--no-publish"])
        .output()
        .expect("run");
    assert!(out.status.success());
    let after = baton::now_unix();
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    let dl = env["deadline_unix"].as_u64().expect("u64");
    assert!(
        dl >= before + baton::DEFAULT_DEADLINE_SECS - 1
            && dl <= after + baton::DEFAULT_DEADLINE_SECS + 1,
        "default deadline outside expected window: {dl} vs [{before}, {after}] + {}",
        baton::DEFAULT_DEADLINE_SECS
    );
}

#[test]
fn acceptance_ac10_override() {
    let before = baton::now_unix();
    let out = Command::new(bin())
        .args([
            "--from", "t", "send", "x", "y",
            "--deadline-secs", "5",
            "--no-publish",
        ])
        .output()
        .expect("run");
    assert!(out.status.success());
    let after = baton::now_unix();
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    let dl = env["deadline_unix"].as_u64().expect("u64");
    assert!(dl >= before + 4 && dl <= after + 6, "override: {dl}");
}
