//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton key <sid> --chord C-c` constructs envelope with method=baton.key, params.chord='C-c', params.repeat defaulting to 1.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac5() {
    let out = Command::new(bin())
        .args([
            "--from", "claude-test-jsy",
            "key", "claude-target-jsy",
            "--chord", "C-c",
            "--no-publish",
        ])
        .output()
        .expect("run baton key");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    assert_eq!(env["method"], "baton.key");
    assert_eq!(env["params"]["chord"], "C-c");
    assert_eq!(env["params"]["repeat"], 1);
}
