//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton peers` reads ~/.cache/baton/surfaces/*.json and emits a JSON array; missing dir is non-fatal (empty array).
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac2_empty_when_missing_dir() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path().join("nonexistent-surfaces");
    let out = Command::new(bin())
        .args(["--json", "--cache-dir"])
        .arg(&dir)
        .arg("peers")
        .output()
        .expect("run baton peers");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let s = String::from_utf8_lossy(&out.stdout);
    let v: serde_json::Value = serde_json::from_str(s.trim()).expect("valid json");
    assert!(v.is_array(), "expected json array, got {s}");
    assert_eq!(v.as_array().unwrap().len(), 0);
}

#[test]
fn acceptance_ac2_lists_present_surfaces() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    let rec = serde_json::json!({
        "session_id": "claude-99-jsy",
        "surface": {"kind": "x11", "window_id": "0x123", "wm_class": "XTerm"},
        "capabilities": {"type": true},
        "claude_version": "test",
        "registered_unix": 1779654473u64,
    });
    std::fs::write(dir.join("claude-99-jsy.json"), serde_json::to_vec(&rec).unwrap()).unwrap();
    let out = Command::new(bin())
        .args(["--json", "--cache-dir"])
        .arg(dir)
        .arg("peers")
        .output()
        .expect("run baton peers");
    assert!(out.status.success());
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    assert_eq!(v.as_array().unwrap().len(), 1);
    assert_eq!(v[0]["session_id"], "claude-99-jsy");
}
