//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: Code contains zero references to TIOCSTI, /dev/pts/, or setterm — verified by a build-time grep test.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::path::Path;

fn walk(p: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = std::fs::read_dir(p) else { return };
    for e in entries.flatten() {
        let path = e.path();
        if path.is_dir() {
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if matches!(name, "target" | ".git" | "tests") {
                continue;
            }
            walk(&path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

#[test]
fn acceptance_ac7() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut files = Vec::new();
    walk(&src, &mut files);
    assert!(!files.is_empty(), "no source files found under src/");

    let forbidden = baton::forbidden_terms();
    for f in &files {
        let body = std::fs::read_to_string(f).expect("read source");
        // Strip blocks bracketed by AC7-SCAN-EXEMPT-START / END markers.
        let mut scanned = String::new();
        let mut skip = false;
        for line in body.lines() {
            if line.contains("AC7-SCAN-EXEMPT-START") {
                skip = true;
                continue;
            }
            if line.contains("AC7-SCAN-EXEMPT-END") {
                skip = false;
                continue;
            }
            if !skip {
                scanned.push_str(line);
                scanned.push('\n');
            }
        }
        for term in forbidden {
            assert!(
                !scanned.contains(*term),
                "forbidden term {term:?} found in {}",
                f.display()
            );
        }
    }
}
