//! Acceptance test for AC12 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `--json` global flag emits machine-readable output for `peers` and `surface` subcommands.
//! Test predicate: tests/acceptance_ac12.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac12` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac12_peers_json() {
    let tmp = TempDir::new().unwrap();
    let out = Command::new(bin())
        .args(["--json", "--cache-dir"])
        .arg(tmp.path())
        .arg("peers")
        .output()
        .expect("run");
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    let _: serde_json::Value = serde_json::from_str(s.trim()).expect("valid json");
}

#[test]
fn acceptance_ac12_surface_json() {
    let tmp = TempDir::new().unwrap();
    let rec = serde_json::json!({
        "session_id": "claude-1-jsy",
        "surface": {"kind": "x11"},
        "registered_unix": 0u64,
    });
    std::fs::write(
        tmp.path().join("claude-1-jsy.json"),
        serde_json::to_vec(&rec).unwrap(),
    )
    .unwrap();
    let out = Command::new(bin())
        .args(["--json", "--cache-dir"])
        .arg(tmp.path())
        .args(["surface", "claude-1-jsy"])
        .output()
        .expect("run");
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    let v: serde_json::Value = serde_json::from_str(s.trim()).expect("valid json");
    assert_eq!(v["session_id"], "claude-1-jsy");
}
