//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton spawn <prompt>` constructs envelope with method=baton.spawn (the renamed delegate.run shim); preserves params.prompt and optional params.cwd.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac6_with_cwd() {
    let out = Command::new(bin())
        .args([
            "--from", "claude-test-jsy",
            "spawn", "do the thing",
            "--target", "claude-target-jsy",
            "--cwd", "/tmp/work",
            "--no-publish",
        ])
        .output()
        .expect("run baton spawn");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    assert_eq!(env["method"], "baton.spawn");
    assert_eq!(env["params"]["prompt"], "do the thing");
    assert_eq!(env["params"]["cwd"], "/tmp/work");
    assert_eq!(env["to"], "claude-target-jsy");
}

#[test]
fn acceptance_ac6_without_cwd() {
    let out = Command::new(bin())
        .args([
            "--from", "claude-test-jsy",
            "spawn", "headless work",
            "--target", "claude-target-jsy",
            "--no-publish",
        ])
        .output()
        .expect("run baton spawn no-cwd");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    assert_eq!(env["method"], "baton.spawn");
    assert!(env["params"].get("cwd").is_none(), "cwd should be absent");
}
