//! Acceptance test for AC9 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: On `cooldown` reply from receiver, `baton send` exits with code 3.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use baton::{ReplyEnvelope, ReplyOutcome, classify_reply, outcome_exit_code};

#[test]
fn acceptance_ac9() {
    let reply = ReplyEnvelope {
        id: "rpc-baton-xxxx".to_string(),
        from: "claude-target-jsy".to_string(),
        ok: false,
        error: Some("cooldown".to_string()),
        detail: None,
        result: None,
    };
    let outcome = classify_reply(&reply);
    assert_eq!(outcome, ReplyOutcome::Cooldown);
    assert_eq!(outcome_exit_code(outcome), 3);
}
