//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton --version` and `baton --help` print without panic; all subcommands have help.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac1() {
    let b = bin();
    assert!(b.exists(), "baton binary not built at {b:?}");

    let v = Command::new(&b).arg("--version").output().expect("run --version");
    assert!(v.status.success(), "--version failed");
    assert!(
        String::from_utf8_lossy(&v.stdout).contains("baton"),
        "--version did not mention baton"
    );

    let h = Command::new(&b).arg("--help").output().expect("run --help");
    assert!(h.status.success(), "--help failed");
    let help = String::from_utf8_lossy(&h.stdout);
    for sub in ["peers", "send", "dry", "key", "spawn", "surface"] {
        assert!(help.contains(sub), "--help missing subcommand: {sub}");
    }

    for sub in ["peers", "send", "dry", "key", "spawn", "surface"] {
        let r = Command::new(&b).args([sub, "--help"]).output().expect("subhelp");
        assert!(r.status.success(), "subcommand `{sub} --help` failed");
    }
}
