//! Acceptance test for AC11 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton surface <sid>` prints the cached surface JSON, exit 0; or `not_found` to stderr and exit 4 if no cache entry.
//! Test predicate: tests/acceptance_ac11.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac11` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac11_present() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    let rec = serde_json::json!({
        "session_id": "claude-99-jsy",
        "surface": {"kind": "tmux", "pane_target": "main:0.0"},
        "capabilities": {"type": true},
        "claude_version": "x",
        "registered_unix": 0u64,
    });
    std::fs::write(dir.join("claude-99-jsy.json"), serde_json::to_vec(&rec).unwrap()).unwrap();
    let out = Command::new(bin())
        .args(["--cache-dir"])
        .arg(dir)
        .args(["surface", "claude-99-jsy"])
        .output()
        .expect("run baton surface");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("claude-99-jsy"));
    assert!(s.contains("tmux"));
}

#[test]
fn acceptance_ac11_not_found() {
    let tmp = TempDir::new().unwrap();
    let out = Command::new(bin())
        .args(["--cache-dir"])
        .arg(tmp.path())
        .args(["surface", "claude-missing-jsy"])
        .output()
        .expect("run baton surface");
    let code = out.status.code().expect("exit code");
    assert_eq!(code, 4, "expected exit 4 for not_found, got {code}");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("not_found"), "stderr: {err}");
}
