//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton dry <sid> <prompt>` resolves a surface from the cache and returns it; publishes nothing when --no-publish is set.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac4() {
    let out = Command::new(bin())
        .args([
            "--from", "claude-test-jsy",
            "dry", "claude-target-jsy", "preview only",
            "--no-publish",
        ])
        .output()
        .expect("run baton dry --no-publish");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let env: serde_json::Value = serde_json::from_slice(&out.stdout).expect("json");
    assert_eq!(env["method"], "baton.send");
    assert_eq!(env["params"]["dry_run"], true);
    assert_eq!(env["params"]["prompt"], "preview only");
    assert_eq!(env["to"], "claude-target-jsy");
}
