//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: `baton send <sid> <prompt>` constructs a valid AGORABUS_RPC envelope with method=baton.send, params.prompt set, and an `id` matching ^rpc-baton-[a-z0-9]+$.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push(if cfg!(debug_assertions) { "debug" } else { "release" });
    p.push("baton");
    p
}

#[test]
fn acceptance_ac3() {
    let out = Command::new(bin())
        .args([
            "--from", "claude-test-jsy",
            "send", "claude-target-jsy", "echo HELLO_BATON",
            "--no-publish",
        ])
        .output()
        .expect("run baton send --no-publish");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let s = String::from_utf8_lossy(&out.stdout);
    let env: serde_json::Value = serde_json::from_str(s.trim()).expect("envelope is json");
    assert_eq!(env["method"], "baton.send");
    assert_eq!(env["from"], "claude-test-jsy");
    assert_eq!(env["to"], "claude-target-jsy");
    assert_eq!(env["params"]["prompt"], "echo HELLO_BATON");
    let id = env["id"].as_str().expect("id is string");
    assert!(id.starts_with("rpc-baton-"), "id shape: {id}");
    let suffix = &id["rpc-baton-".len()..];
    assert!(
        suffix.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit()),
        "suffix chars: {suffix}"
    );
}
