//! Acceptance test for AC8 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: baton (cli)
//! AC description: On `unreachable` reply from receiver, `baton send` exits with code 2 and prints the resolved surface to stderr.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use baton::{ReplyEnvelope, ReplyOutcome, classify_reply, outcome_exit_code};

#[test]
fn acceptance_ac8() {
    let reply = ReplyEnvelope {
        id: "rpc-baton-xxxx".to_string(),
        from: "claude-target-jsy".to_string(),
        ok: false,
        error: Some("unreachable".to_string()),
        detail: Some("x11/0x4a00007".to_string()),
        result: None,
    };
    let outcome = classify_reply(&reply);
    assert_eq!(outcome, ReplyOutcome::Unreachable);
    assert_eq!(outcome_exit_code(outcome), 2);
}
